# Generated by Django 5.2.8 on 2025-12-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_bank_account_number_profile_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
