# Generated by Django 5.2.8 on 2025-12-08 12:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_usdt_wallet_address_bankwithdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_uuid',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(db_index=True, default=api.models.generate_unique_ticket_code, max_length=8, unique=True),
        ),
    ]
