# Generated by Django 5.2.8 on 2025-12-08 12:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ticket_ticket_uuid_ticket_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(db_index=True, default=api.models.generate_ticket_code_for_default, max_length=8, unique=True),
        ),
    ]
