# Generated by Django 5.2.8 on 2025-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ticket_ticket_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotterySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
    ]
