# Generated by Django 5.2.8 on 2025-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/Avatar_Aang.png', null=True, upload_to='avatars/'),
        ),
    ]
